apiVersion: v1
kind: Namespace
metadata:
  name: dynamic-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engagement-backend
  namespace: dynamic-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: api
        # ⬇️ Updated to match your custom backend image name
        image: venka/microservice-upvote-backend:84ffc1f7dd8ede4e0dd290b8f606d63c310dc3f6
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dynamic-apps
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engagement-frontend
  namespace: dynamic-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: ui
        # ⬇️ Updated to match your custom frontend image name
        image: venka/microservice-upvote-frontend:84ffc1f7dd8ede4e0dd290b8f606d63c310dc3f6
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_API_URL
          value: "http://backend-service.dynamic-apps.svc.cluster.local:8080" # CoreDNS Internal Private Mapping
---
apiVersion: v1
kind: Service
metadata:
  name: public-frontend-svc
  namespace: dynamic-apps
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
